# Generated by Django 6.0.1 on 2026-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_managers_rename_license_users_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='perfil',
            field=models.CharField(choices=[('', 'Selecione um perfil'), ('full', 'Administrador'), ('basic', 'Básico'), ('view', 'Visualizador')], max_length=10),
        ),
    ]
