# Generated by Django 6.0.1 on 2026-01-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vaga',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vaga'),
        ),
    ]
