# Generated by Django 6.0.1 on 2026-01-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='perfil',
            field=models.CharField(choices=[('', 'Selecione um perfil'), ('full', 'Administrador'), ('basic', 'Básico')], max_length=10),
        ),
    ]
