# Generated by Django 6.0.1 on 2026-01-17 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wpm_average', models.FloatField(help_text='Velocidade média em palavras por minuto')),
                ('accuracy_average', models.FloatField(help_text='Acurácia média em percentual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teste de Digitação',
                'verbose_name_plural': 'Testes de Digitação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingTestPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(choices=[(1, 'Fase 1'), (2, 'Fase 2'), (3, 'Fase 3')])),
                ('original_phrase', models.TextField(help_text='Frase original a ser digitada')),
                ('typed_text', models.TextField(help_text='Texto digitado pelo usuário')),
                ('time_seconds', models.FloatField(help_text='Tempo gasto em segundos')),
                ('wpm', models.FloatField(help_text='Velocidade em palavras por minuto')),
                ('accuracy', models.FloatField(help_text='Acurácia em percentual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('typing_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.typingtest')),
            ],
            options={
                'verbose_name': 'Fase do Teste de Digitação',
                'verbose_name_plural': 'Fases dos Testes de Digitação',
                'ordering': ['typing_test', 'phase_number'],
                'unique_together': {('typing_test', 'phase_number')},
            },
        ),
    ]
