# Generated by Django 6.0.1 on 2026-01-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quadrant_a_score', models.IntegerField(help_text='Score do Quadrante A - Analítico (Lógico)')),
                ('quadrant_b_score', models.IntegerField(help_text='Score do Quadrante B - Prático (Administrativo)')),
                ('quadrant_c_score', models.IntegerField(help_text='Score do Quadrante C - Relacional (Interpessoal)')),
                ('quadrant_d_score', models.IntegerField(help_text='Score do Quadrante D - Inovador (Criativo)')),
                ('dominant_quadrant', models.CharField(choices=[('A', 'Pensador Analítico'), ('B', 'Pensador Prático'), ('C', 'Pensador Relacional'), ('D', 'Pensador Inovador')], help_text='Quadrante com maior score', max_length=1)),
                ('answers', models.JSONField(help_text='Respostas completas do teste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Comportamental',
                'verbose_name_plural': 'Perfis Comportamentais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_test_completed', models.BooleanField(default=False, help_text='Teste de digitação completado')),
                ('typing_test_completed_at', models.DateTimeField(blank=True, help_text='Data de conclusão do teste de digitação', null=True)),
                ('behavioral_test_completed', models.BooleanField(default=False, help_text='Teste de perfil comportamental completado')),
                ('behavioral_test_completed_at', models.DateTimeField(blank=True, help_text='Data de conclusão do teste de comportamento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Teste',
                'verbose_name_plural': 'Progresso dos Testes',
            },
        ),
    ]
